name: aqim
description: "Aqim - Prayer Times & Qibla app for Malaysia. Accurate Malaysian prayer times, automatic azan, qibla compass, daily duas, and beautiful home screen widgets."
publish_to: 'none'

version: 1.0.4+4

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  shimmer: ^3.0.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  flutter_timezone: ^5.0.0
  timezone: ^0.10.1
  permission_handler: ^12.0.1
  flutter_launcher_icons: ^0.14.4
  flutter_screenutil: ^5.9.3
  home_widget: ^0.8.1
  flutter_svg: ^2.2.1
  carousel_slider: ^5.1.1
  url_launcher: ^6.3.2
  google_mobile_ads: ^6.0.0
  wakelock_plus: ^1.3.3
  flex_seed_scheme: ^4.0.1
  google_mlkit_pose_detection: ^0.14.0
  camera: ^0.11.3
  google_mlkit_image_labeling: ^0.14.1
  flutter_compass: ^0.8.0
  qr_flutter: ^4.1.0
  audioplayers: ^6.1.0
  
  vibration: ^3.1.4
  screen_brightness: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/appicon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/
    - assets/icon/
    - assets/fonts/
    - assets/svg/
    - assets/lottie/
    - assets/json/


  fonts:
    - family: Aqim
      fonts:
        - asset: assets/fonts/Aqim.ttf

    # --- Arabic Font: Lateef ---
    - family: Lateef
      fonts:
        - asset: assets/fonts/Lateef-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Lateef-Light.ttf
          weight: 300
        - asset: assets/fonts/Lateef-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lateef-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lateef-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Lateef-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lateef-ExtraBold.ttf
          weight: 800

    # --- Arabic Font: Scheherazade New ---
    - family: ScheherazadeNew
      fonts:
        - asset: assets/fonts/ScheherazadeNew-Regular.ttf
          weight: 400
        - asset: assets/fonts/ScheherazadeNew-Medium.ttf
          weight: 500
        - asset: assets/fonts/ScheherazadeNew-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ScheherazadeNew-Bold.ttf
          weight: 700
